name: release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'action.yml'
      - 'functions/**'

jobs:
  release:
    runs-on: ubuntu-latest
    name: 'Publish a new release'
    steps:

    - uses: arwynfr/actions-conventional-versioning@1.0.3
      with:
        pattern: ''